swisslos_balancing:
  top_p: 0.3
  n_games_threshold: 1000
  random_state: 42

pre_train:
  hidden_dim: 10
  n_layers: 5
  learning_rate: 1e-4
  batch_size: 500000
  max_epochs: 10000
  early_stop_patience: 20

fine_tune:
  learning_rate: 1e-5
  batch_size: 500000
  max_epochs: 10000
  early_stop_patience: 100

evaluate_trump_model:
  checkpoint_path: dvclive/artifacts/trump_selection_pre_trained.ckpt
  time_budget: 0.05
  n_sets: 128
  points_threshold: 1000
  num_workers: 16
