swisslos_balancing:
  top_p: 0.2
  n_games_threshold: 1000
  random_state: 42

pre_train:
  hidden_dim: 50
  n_layers: 3
  learning_rate: 1e-3
  batch_size: 500000
  max_epochs: 5
  early_stop_patience: 5

fine_tune:
  learning_rate: 1e-5
  batch_size: 500000
  max_epochs: 25
  early_stop_patience: 100

evaluate_trump_model:
  checkpoint_path: dvclive/artifacts/trump_selection.ckpt
  time_budget: 0.1
  n_sets: 32
  points_threshold: 1000
  num_workers: 16
