swisslos_balancing:
  top_p: 0.2
  n_games_threshold: 1000
  random_state: 42

pre_train:
  hidden_dim: 128
  n_layers: 16
  dropout_rate: 0.1
  learning_rate: 5e-3
  batch_size: 150000
  max_epochs: 250
  early_stop_patience: 30

fine_tune:
  learning_rate: 1e-3
  batch_size: 150000
  max_epochs: 20000
  early_stop_patience: 50

evaluate_trump_model:
  checkpoint_path: dvclive/artifacts/trump_selection.ckpt
  time_budget: 0.05
  n_sets: 128
  points_threshold: 1000
  num_workers: 16
