swisslos_balancing:
  top_p: 0.2
  n_games_threshold: 1000
  random_state: 42

pre_train:
  hidden_dim_factor: 1
  n_layers: 5
  dropout_rate: 0.0
  learning_rate: 1e-3
  batch_size: 500000
  max_epochs: 150
  early_stop_patience: 30

fine_tune:
  learning_rate: 5e-4
  batch_size: 500000
  max_epochs: 2500
  early_stop_patience: 50

evaluate_trump_model:
  checkpoint_path: dvclive/artifacts/trump_selection.ckpt
  time_budget: 0.05
  n_sets: 128
  points_threshold: 1000
  num_workers: 16
