stages:
  swisslos_balancing:
    cmd: python swisslos_balancing.py
    deps:
    - swisslos_balancing.py
    - data/2018_10_18_trump.csv
    - data/player_all_stat.json
    params:
    - swisslos_balancing.n_games_threshold
    - swisslos_balancing.random_state
    - swisslos_balancing.top_p
    outs:
    - data/swisslos_balanced.csv
  graf_pretrain:
    cmd: python training.py graf
    deps:
    - training.py
    - data/graf-dataset-balanced
    params:
    - train.hidden_dim
    - train.n_layers
    - train.learning_rate
    - train.batch_size
    - train.max_epochs
    - train.early_stop_patience
    # TODO artifacts and metrics and stuff
    outs:
      - dvclive/artifacts/trump_selection.ckpt
