stages:
  swisslos_balancing:
    cmd: python swisslos_balancing.py
    deps:
    - swisslos_balancing.py
    - data/2018_10_18_trump.csv
    - data/player_all_stat.json
    params:
    - swisslos_balancing.n_games_threshold
    - swisslos_balancing.random_state
    - swisslos_balancing.top_p
    outs:
    - data/swisslos_balanced.csv
  graf_pretrain:
    cmd: python training.py graf
    deps:
    - training.py
    - data/graf-dataset-balanced
    params:
    - pre_train.hidden_dim
    - pre_train.n_layers
    - pre_train.learning_rate
    - pre_train.batch_size
    - pre_train.max_epochs
    - pre_train.early_stop_patience
    outs:
    - dvclive/artifacts/trump_selection.ckpt
  swisslos_finetuning:
    cmd: python training.py swisslos dvclive/artifacts/trump_selection.ckpt
    deps:
      - training.py
      - data/swisslos_balanced.csv
    params:
      - fine_tune.learning_rate
      - fine_tune.batch_size
      - fine_tune.max_epochs
      - fine_tune.early_stop_patience
    outs:
      - dvclive/artifacts/trump_selection.ckpt
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  best:
    path: dvclive/artifacts/trump_selection.ckpt
    type: model
