swisslos_balancing:
  top_p: 0.2
  n_games_threshold: 1000
  random_state: 42

pre_train:
  hidden_dim: 50
  n_layers: 3
  learning_rate: 1e-3
  batch_size: 200000
  max_epochs: 150
  early_stop_patience: 5

fine_tune:
  learning_rate: 1e-5
  batch_size: 15000
  max_epochs: 20000
  early_stop_patience: 50
