hidden_dim: 128
n_layers: 16
learning_rate: 0.005
dropout_rate: 0.1
train_path: data/graf-dataset-balanced/train/
val_path: data/graf-dataset-balanced/val/
batch_size: 150000
num_workers: 4
csv_path: data/swisslos_balanced.csv
test_split: 0
val_split: 0.2
