hidden_dim_factor: 1
n_layers: 5
learning_rate: 0.001
dropout_rate: 0.0
train_path: data/graf-dataset-balanced/train/
val_path: data/graf-dataset-balanced/val/
batch_size: 500000
num_workers: 4
csv_path: data/swisslos_balanced.csv
test_split: 0
val_split: 0.2
